name: CI

on:
  push:
    branches: [test]

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Read file.txt
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./file.txt

      - name: Echo file.txt
        run: echo ${{ steps.package.outputs.content }}
